### ISSUE TITLE
New line insertion breaks markdown

### ISSUE THREAD

**Issue by xzyfer** [xzyfer/distancss#8]
``` scss
/**
 * @section #next-minor
 *
 * Spacing class builder
 *
 * Spacing classes are build following this recipe:
 * `<type>-<size>-([direction]-[viewport])`
 *
 * Available values for each token are as follows:
 *
 * ### size
 *
 * | Size       | Token   |
 * | :--------- | :------ |
 * | 0          | `none`  |
 */
$_spacings: get-spacings();
@for $i from 1 through length($_spacings) {
    $spacing: nth($_spacings, $i);
    /* | #{nth($spacing, 2)} | `#{nth($spacing, 1)}` | */
}
/**
 *
 * @Markup
 * <div class="docs-box m-text-bottom">Bottom text margin</div>
 *
 * @default
 *
 * @endsection
 */
```
